[package]
name = "private_executor_lite"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.0"

[dev-dependencies]
snforge_std = "0.55.0"
assert_macros = "2.15.0"
cairo_test = "2.15.0"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
